### ISSUE TITLE
Statistiques d'un Pokemon

### ISSUE THREAD

**Issue by arthurdeschamps** [unige-semantics-2017/information#2]
Je ne suis pas sûr de comprendre comment gérer la propriété "effective_stats" de la structure Pokemon.
D'après moi, la seule propriété d'effective_stats qui change est la propriété hitpoints, qui prendrait donc directement la valeur hitpoints de Pokemon (au lieu du hitpoints de l'espèce). Est-ce que je me trompe?
Mais le problème est que hitpoints est déclaré constant dans Pokemon, donc il n'est sensé pas changer non plus.

**Comment by saucisson** [comment]
Les `effective_stats` sont les valeurs calculées pour tous les champs d'une structure `Stats`. On voit très bien le calcul [ici](http://bulbapedia.bulbagarden.net/wiki/Statistic#In_Generation_III_onward). Ces stats dépendent des individual values, base values et effort values.

**Comment by arthurdeschamps** [comment]
Ok je vois, merci.
Du coup, concernant le paramètre "Level" dans la formule, il faut aussi faire suivant chaque Type de Pokemon ? (Regarder quel est le facteur multiplicatif pour chaque type)

**Comment by saucisson** [comment]
Le level, c'est le niveau du pokemon, il me semble.

**Comment by arthurdeschamps** [comment]
Oups, je voulais dire "Nature"

**Comment by saucisson** [comment]
Alors oui, bien sûr.

**Comment by arthurdeschamps** [comment]
Ok très bien merci.
